config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index]
  post '/basket', to: 'orders#basket', as: 'basket'
  delete '/remove_order', to: 'orders#remove_order', as: 'remove_order'
  put '/update_basket', to: 'orders#update_basket', as: 'update_basket'
  put '/checkout', to: 'orders#checkout', as: 'checkout'
  root 'orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  
  belongs_to :product
  
  def self.build_order(item)
    b = find_by_user_cookie_and_product_id_and_status(item["user_uniq"],item["prod"],"order") || new()
    b.scan(item)
  end
  
  def scan(i)
    self.product_id = i["prod"]
    self.user_cookie = i["user_uniq"]
    self.qty = self.id.present? ? (self.qty + i["qty"].to_i) : i["qty"].to_i
    self.save
  end
  
  def total
    if self.product.code == "01"
      _price = self.qty * self.product.price.to_f  
      # count second flag
      _count = (self.qty / 2) * 5
      _price - _count
    else
      _price = self.qty * self.product.price.to_f
      _vat_price = _price * (self.product.vat.percent.to_f / 100)
      _price + _vat_price
        
    end
  end
  
  def self.update_order(item)
    _basket_data = {}
    _basket = find(item["basket"]) 
    _basket.qty = item["qty"]
    _basket.save(validate: false)
    _basket_data["sub_total_format"] = number_to_currency(_basket.total,:unit=>'€')
    _basket_data["sub_total"] = _basket.total
    _basket_data
  end
  
  def discount
    
  end
  
end

app/models/basket_detail.rb
class BasketDetail < ApplicationRecord
  belongs_to :basket
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vat
end

app/models/vat.rb
class Vat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :insert_session_id, only: [:index, :basket, :update_basket]
  before_action :get_order, only: [:index, :basket]

  
  def index
    # get the browser cookies
    @baskets_subtotal = @baskets.present? ? @baskets.sum(&:sub_total_price) : 0
    @products = Product.all
  end
  
  def basket        
    Basket.build_order(params)
    @baskets_subtotal = @baskets.present? ? @baskets.sum(&:sub_total_price) : 0
    respond_to do |format|
      format.js 
    end
  end
    
  def update_basket
    @basket = Basket.update_order(params)
    respond_to do |format|
      format.json {
        render json: {basket: @basket}
      }
    end
  end
  
  def remove_order
    @basket = Basket.find(params[:basket])
    @basket.destroy
  end
  
  def checkout
    @baskets = Basket.where(user_cookie: session[:session_id]).update_all(email: params[:email], phone: params[:phone], status: "checkout")
    session[:session_id] = nil
    redirect_to root_path
  end
  
  private
  
  def get_order
    @baskets = BasketDecorator.decorate_collection(Basket.where(user_cookie: session[:session_id],status: "order"))
  end
  
  def insert_session_id
    params[:user_uniq] = session[:session_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  
  #def prod_code(p)
  #  p.product.code
  #end
  #
  #def prod_name(p)
  #  p.product.name
  #end
  #
  #def prod_price   (p) 
  #  number_to_currency(p.product.price,:unit=>'€')
  #end
  #
  #def prod_qty(p)
  #  p.qty
  #end
  #
  #def prod_vat(p)
  #  "#{p.product.vat.name}(#{p.product.vat.percent}%)"
  #end
  #
  #def sub_total(p)    
  #  number_to_currency(p.total,:unit=>'€')
  #end
  #
  #def sub_total_price(p)
  #  subtotal(p.total)
  #  p.total
  #end
  #
  #def subtotal(total)
  #  number_to_currency(total,:unit=>'€')
  #end
  
  def discount(total)
    if total >= 70    
      (total * 12 / 100)
    else
      0
    end
  end
  
  def total_order(total)
    if total >= 70    
      total - (total * 12 / 100) 
    else
      total
    end
  end
  
end

app/views/layouts/_admin_lte_2_header.html.haml
%body
  %header.main-header
    / Logo
    %a.logo{:href => "/"}
      / mini logo for sidebar mini 50x50 pixels
      %span.logo-mini
        %b> A
        LT
      / logo for regular state and mobile devices
      %span.logo-lg
        %b> Admin
        LTE
    / Header Navbar
    %nav.navbar.navbar-static-top{:role => "navigation"}
      / Sidebar toggle button
      %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
        %span.sr-only Toggle navigation
      / Navbar Right Menu
      .navbar-custom-menu
        %ul.nav.navbar-nav
          / Messages: style can be found in dropdown.less
          %li.dropdown.messages-menu
            / Menu toggle button
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.fa.fa-envelope-o
              %span.label.label-success 4
            %ul.dropdown-menu
              %li.header You have 4 messages
              %li
                / inner menu: contains the messages
                %ul.menu
                  %li
                    / start message
                    %a{:href => "#"}
                      .pull-left
                        / User Image
                        %img.img-circle{:alt => "User Image", :src => "/assets/user2-160x160.jpg"}/
                      / Message title and timestamp
                      %h4
                        Support Team
                        %small
                          %i.fa.fa-clock-o
                          5 mins
                      / The message
                      %p Why not buy a new awesome theme?
                  / end message
                / /.menu
              %li.footer
                %a{:href => "#"} See All Messages
          / /.messages-menu
          / Notifications Menu
          %li.dropdown.notifications-menu
            / Menu toggle button
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.fa.fa-bell-o
              %span.label.label-warning 10
            %ul.dropdown-menu
              %li.header You have 10 notifications
              %li
                / Inner Menu: contains the notifications
                %ul.menu
                  %li
                    / start notification
                    %a{:href => "#"}
                      %i.fa.fa-users.text-aqua
                      5 new members joined today
                  / end notification
              %li.footer
                %a{:href => "#"} View all
          / Tasks Menu
          %li.dropdown.tasks-menu
            / Menu Toggle Button
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.fa.fa-flag-o
              %span.label.label-danger 9
            %ul.dropdown-menu
              %li.header You have 9 tasks
              %li
                / Inner menu: contains the tasks
                %ul.menu
                  %li
                    / Task item
                    %a{:href => "#"}
                      / Task title and progress text
                      %h3
                        Design some buttons
                        %small.pull-right 20%
                      / The progress bar
                      .progress.xs
                        / Change the css width attribute to simulate progress
                        .progress-bar.progress-bar-aqua{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
                          %span.sr-only 20% Complete
                  / end task item
              %li.footer
                %a{:href => "#"} View all tasks
          / User Account Menu
          %li.dropdown.user.user-menu
            / Menu Toggle Button
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              / The user image in the navbar
              %img.user-image{:alt => "User Image", :src => "/assets/user2-160x160.jpg"}/
              / hidden-xs hides the username on small devices so only the image appears.
              %span.hidden-xs Alexander Pierce
            %ul.dropdown-menu
              / The user image in the menu
              %li.user-header
                %img.img-circle{:alt => "User Image", :src => "/assets/user2-160x160.jpg"}/
                %p
                  Alexander Pierce - Web Developer
                  %small Member since Nov. 2012
              / Menu Body
              %li.user-body
                .col-xs-4.text-center
                  %a{:href => "#"} Followers
                .col-xs-4.text-center
                  %a{:href => "#"} Sales
                .col-xs-4.text-center
                  %a{:href => "#"} Friends
              / Menu Footer
              %li.user-footer
                .pull-left
                  %a.btn.btn-default.btn-flat{:href => "#"} Profile
                .pull-right
                  %a.btn.btn-default.btn-flat{:href => "#"} Sign out
          %li
            %a{"data-toggle" => "control-sidebar", :href => "#"}
              %i.fa.fa-gears

app/views/layouts/_admin_lte_2_sidebar.html.haml
/ Left side column. contains the logo and sidebar
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel (optional)
    .user-panel
      .pull-left.image
        %img.img-circle{:alt => "User Image", :src => "/assets/user2-160x160.jpg"}/
      .pull-left.info
        %p Alexander Pierce
        / Status
        %a{:href => "#"}
          %i.fa.fa-circle.text-success
          Online
    / search form (Optional)
    %form.sidebar-form{:action => "#", :method => "get"}
      .input-group
        %input.form-control{:name => "q", :placeholder => "Search...", :type => "text"}/
        %span.input-group-btn
          %button#search-btn.btn.btn-flat{:name => "search", :type => "submit"}
            %i.fa.fa-search
    / /.search form
    / Sidebar Menu
    %ul.sidebar-menu
      %li.header HEADER
      / Optionally, you can add icons to the links
      %li.active
        %a{:href => "#"}
          %i.fa.fa-link
          %span Link
      %li
        %a{:href => "#"}
          %i.fa.fa-link
          %span Another Link
      %li.treeview
        %a{:href => "#"}
          %i.fa.fa-link
          %span Multilevel
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            %a{:href => "#"} Link in level 2
          %li
            %a{:href => "#"} Link in level 2
    / /.sidebar-menu
  / /.sidebar

app/views/layouts/admin_lte_2.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1 test
    = yield

app/views/layouts/application.html.haml
%html
  %head
    %title StoreAPP
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body.hold-transition.skin-blue.layout-top-nav
    .wrapper
      %header.main-header
        %nav.navbar.navbar-static-top
          .container
            .navbar-header
              %a.navbar-brand{:href => "#"}
                %b> Store

      
      .content-wrapper
        .container
          // main content
          = yield

app/views/orders/_basket.html.haml
.table-responsive
  %table.table.table-bordered
    %thead
      %tr
        %th.text-center Action
        %th.text-center Code
        %th.text-center Name
        %th.text-center Price
        %th.text-center Qty
        %th.text-center Vat Rate
        %th.text-center Subtotal
    %tbody
      - @baskets.each do |p|
        %tr
          %td 
            %p.remove_data= link_to "Remove", 'javascript:void(0)', class: "remove_product"
          %td= p.prod_code
          %td.col-md-5= p.prod_name
          %td= p.prod_price
          %td.col-md-1
            = text_field_tag 'qty', p.prod_qty, class: "change_qty form-control", onkeypress: 'return event.charCode >= 48 && event.charCode <= 57'
            = hidden_field_tag 'basket', p.id
          %td= p.prod_vat
          %td
            %p.basket_price= p.sub_total
            = hidden_field_tag 'sub_total_basket', p.sub_total_price, class: "sub_total_basket"

      %tr
        %td{:colspan => "6"}
          .pull-right
            %b
              Subtotal:
        %td
          %b.sub_total_order 
            = number_to_currency(@baskets_subtotal,:unit=>'€')

      %tr
        %td{:colspan => "6"}
          .pull-right
            Discount(12%):
        %td
          %p.discount= number_to_currency(discount(@baskets_subtotal),:unit=>'€')

      %tr
        %td{:colspan => "6"}
          .pull-right
            %b
              Grand Total:
        %td
          %b.total_order  
            = number_to_currency(total_order(@baskets_subtotal),:unit=>'€')
#checkout{style:"display:#{@baskets_subtotal != 0 ? '' : 'none'};"}      
  .col-md-6  
    = form_tag checkout_path, method: :put do      
      .form-group  
        = email_field_tag "email",nil, class:"form-control form-control-solid placeholder-no-fix", placeholder: "Email", required: true
      .form-group  
        = text_field_tag "phone", nil, class: "form-control form-control-solid placeholder-no-fix", placeholder: "Phone", required: true
      .form-group
        .pull-right
          = submit_tag "Proceed to Checkout", class: "btn btn-default btn-md"              

  
  
                  

app/views/orders/basket.js.haml
:plain
  $('#baskets').html("#{raw escape_javascript(render 'basket')}");

app/views/orders/index.html.haml
%section.content
  // info alert
  .basket
    .box.box-default
      .box-header.with-border
        %h3.box-title
          Basket
      .box-body
        .row
          .col-md-12
            #baskets= render 'basket'
  .box.box-primary
    .box-header.with-border
      %h3.box-title
        Products
  
    .box-body
      .row
        .col-md-12
          - @products.each do |p|
            .row.col-md-4.text-center
              %h3= p.name
              .row
                .col-md-6
                  = hidden_field_tag 'qty', 1, class: 'form-control qty'
                  = hidden_field_tag 'product_id', p.id, class: "prod_id"
                .col-md-12
                  .text-center
                    = submit_tag "Add to Cart", class: 'btn btn-primary btn-sm btn-flat add_to_cart', remote: true